### ISSUE TITLE
Backchannel Chat

### ISSUE THREAD

**Issue by superphly** [MADindustries/WhatManager2#40]
Is there a place to chat/ask questions?

**Comment by MADindustries** [comment]
Well there was #wm2 on the RED IRC, but it's been overrun by spam lately. That said, I'm happy to discuss directly via irc or start a new channel. Perhaps there's a thread at RED.

**Comment by MADindustries** [comment]
I am considering starting a slack for it. Would that work?

**Comment by superphly** [comment]
Telegram? Discord?

**Comment by superphly** [comment]
Can you shoot me an email? superphly@g

**Comment by MADindustries** [comment]
Sent

**Comment by MADindustries** [comment]
Did you ever get my telegram? Just want to make sure I didn't miss you
